### PR TITLE
Update nvmrc to v20.9.0

### PR DESCRIPTION
**Pull request by smaye81**
This updates the .nvmrc file to always use the latest minor version of Node v20 (current LTS)

### CODE REVIEW

**Review by timostamm — APPROVED** [review]

**Comment by smaye81** [comment]
@timostamm wdyt about this instead to always use the latest LTS?

**Comment by timostamm** [comment]
Maybe? I'm not sure that it's supported by all things that read .nvmrc files. Is that standardized anywhere? I'm also a bit worried that it will update the major version on a whim - npm, which is tied to Node.js, is used heavily in build and release.

**Comment by smaye81** [comment]
It looks like nvm and fnm both support it, but your other point about major versions is probably more salient here. Maybe we go with 20.x so that we at least stay updated within a major version?

**Comment by timostamm** [comment]
If `20.x` works, this sounds good to me.

**Review by timostamm — APPROVED** [review]

**Pull request merged**
