### PR TITLE
adding support for Nestjs

### PR DESCRIPTION
**Pull request by stevenceuppens**
Draft Proposal

New connect-nest package to natively support Buf Connect in Nestjs.

This packages uses [NestMiddleware](https://docs.nestjs.com/middleware) to integrate with Buf Connect with the underlying express or fastify server (agnostic implementation).

### CODE REVIEW

**Comment by srikrsna-buf** [comment]
Hey! Thank you for the PR! 

We are discussing how to handle framework integrations going forward. I'd suggest holding off until I get back to you with how we want to incorporate such packages.

**Comment by srikrsna-buf** [comment]
@stevenceuppens Can you open an RFC similar to this [one](https://github.com/connectrpc/connectrpc.com/pull/123) proposing a new repo for the nestjs framework? We are not familiar with nestjs and would like someone with nestjs experience to be a co-maintainer of that repo, are you open to maintaining it in the long term?

**Comment by srikrsna-buf** [comment]
@stevenceuppens closing this issue, please open an RFC if you want to add the package. Thanks!

**Comment by boan-anbo** [comment]
Good effort but this won't give access to DI to the Connect endpoints, they will end up with undefined injected services because it's currently used as global middleware.

https://docs.nestjs.com/middleware#global-middleware

**Pull request closed without merging**
